Repository WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp, pull requests merged in 2023-04, with the labels that each got.

#75 Board members and staffs displayed on the same About us page
  front-end/index-vue/public/members.json
  front-end/index-vue/src/components/AboutUs.vue
Labels: sprint, high

#76 Added specialty pages
  front-end/index-vue/public/Resources.json
  front-end/index-vue/public/members.json
  front-end/index-vue/public/specialties.json
  front-end/index-vue/src/components/Specialty.vue
  front-end/index-vue/src/router/index.js
Labels: sprint, high

#77 Added Resource pages
  front-end/index-vue/public/Resources.json
  front-end/index-vue/src/App.vue
  front-end/index-vue/src/components/AboutUs.vue
  front-end/index-vue/src/components/EventsPage.vue
  front-end/index-vue/src/components/Resource.vue
  front-end/index-vue/src/components/Resources.vue
  front-end/index-vue/src/components/Specialty.vue
  front-end/index-vue/src/router/index.js
Labels: sprint, high

#78 Sprint5/editor app resources tab
  index-editor-app/index-editor-app-engine/AddImageHandler.cs
  index-editor-app/index-editor-app-engine/EditorInstances.cs
  index-editor-app/index-editor-app-engine/EventsHandler.cs
  index-editor-app/index-editor-app-engine/Icons.cs
  index-editor-app/index-editor-app-engine/IndexAPIClient.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Events.cs
  index-editor-app/index-editor-app-engine/JsonClasses/IndexImageList.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Resources.cs
  index-editor-app/index-editor-app-engine/JsonClasses/SaveLoad.cs
  index-editor-app/index-editor-app-engine/MembersHandler.cs
  index-editor-app/index-editor-app-engine/NewsHandler.cs
  index-editor-app/index-editor-app-engine/ResourcesHandler.cs
  index-editor-app/index-editor-app-engine/SaveLoad.cs
  index-editor-app/index-editor-app-engine/SpecialtyHandler.cs
  index-editor-app/index-editor-app/EventsForm.cs
  index-editor-app/index-editor-app/Form1.Designer.cs
  index-editor-app/index-editor-app/Form1.cs
  index-editor-app/index-editor-app/Form1.resx
  index-editor-app/index-editor-app/ImageForm.cs
  index-editor-app/index-editor-app/Members.cs
  index-editor-app/index-editor-app/NewsForm.cs
  index-editor-app/index-editor-app/ResoucresForm.cs
  index-editor-app/index-editor-app/SpecialtiesForm.cs
  index-editor-app/index-editor-app/index-editor-app.csproj.user
Labels: enhancement

#79 Sprint6/aws terraform
  README.md
  terraform/.terraform.lock.hcl
  terraform/api_gateway.tf
  terraform/main.tf
  terraform/s3.tf
Labels: documentation, enhancement

#80 Added Sprin 6 contact page
  Sprint Report/Sprint6-Report.md
Labels: sprint, high

#82 Added Json Schemas and validation button to all tabs
  index-editor-app/index-editor-app-engine/AddImageHandler.cs
  index-editor-app/index-editor-app-engine/EventsHandler.cs
  index-editor-app/index-editor-app-engine/JsonExamples/events.json
  index-editor-app/index-editor-app-engine/JsonExamples/indeximages.json
  index-editor-app/index-editor-app-engine/JsonExamples/members.json
  index-editor-app/index-editor-app-engine/JsonExamples/news.json
  index-editor-app/index-editor-app-engine/JsonExamples/resources.json
  index-editor-app/index-editor-app-engine/JsonExamples/specialties.json
  index-editor-app/index-editor-app-engine/JsonSchemas/eventsSchema.json
  index-editor-app/index-editor-app-engine/JsonSchemas/indeximagesSchema.json
  index-editor-app/index-editor-app-engine/JsonSchemas/membersSchema.json
  index-editor-app/index-editor-app-engine/JsonSchemas/newsSchema.json
  index-editor-app/index-editor-app-engine/JsonSchemas/resourcesSchema.json
  index-editor-app/index-editor-app-engine/JsonSchemas/specialtiesSchema.json
  index-editor-app/index-editor-app-engine/MembersHandler.cs
  index-editor-app/index-editor-app-engine/NewsHandler.cs
  index-editor-app/index-editor-app-engine/ResourcesHandler.cs
  index-editor-app/index-editor-app-engine/SpecialtyHandler.cs
  index-editor-app/index-editor-app-engine/index-editor-app-engine.csproj
  index-editor-app/index-editor-app/EventsForm.cs
  index-editor-app/index-editor-app/Form1.Designer.cs
  index-editor-app/index-editor-app/ImageForm.cs
  index-editor-app/index-editor-app/Members.cs
  index-editor-app/index-editor-app/NewsForm.cs
  index-editor-app/index-editor-app/ResoucresForm.cs
  index-editor-app/index-editor-app/SpecialtiesForm.cs
Labels: enhancement

#83 Fixed errors when saving and loading
  index-editor-app/index-editor-app-engine/MembersHandler.cs
  index-editor-app/index-editor-app-engine/SaveLoad.cs
  index-editor-app/index-editor-app/Form1.cs
Labels: Bug fix

#84 Added different branches to contact page
  front-end/index-vue/public/Contact.json
  front-end/index-vue/src/components/Contact.vue
  front-end/index-vue/src/components/Contacts.vue
  front-end/index-vue/src/router/index.js
Labels: sprint, high

#85 Fixed resource deployment bugs including post and dependant resources…
  terraform/.gitignore
  terraform/api_gateway.tf
  terraform/main.tf
  terraform/s3.tf
Labels: Bug fix

#86 Sprint7/terraform workflow
  .github/workflows/workflow.yml
  terraform/s3.tf
Labels: enhancement, Development Testing

#87 Added terraform state bucket and dynamodb lock
  terraform/main.tf
  terraform/remote_state.tf
  terraform/s3.tf
Labels: Development Testing

#88 Uncommented upload build files
  terraform/s3.tf
Labels: Bug fix

#89 updated vue build files path in terraform
  terraform/s3.tf
Labels: Bug fix

#90 fixing vue build process
  .github/workflows/workflow.yml
Labels: Bug fix

#91 fixing vue build and deployment
  .github/workflows/workflow.yml
  terraform/s3.tf
Labels: Bug fix

#96 Added Sprint report for sprint 7
  Sprint Report/sprint7-Report.md
  front-end/index-vue/package-lock.json
Labels: documentation, sprint
