Repository WSUCptSCapstone-Fall2022Spring2023/index-fullstackapp, pull requests merged in 2023-02, with the labels that each got.

#46 Sprint1/about us page
  front-end/index-vue/public/members.json
  front-end/index-vue/src/components/AboutUs.vue
  front-end/index-vue/src/components/NewsPage.vue
Labels: sprint, high

#47 Sprint1/editor app members
  index-editor-app/Class1.cs
  index-editor-app/index-editor-app-engine/IndexAPIClient.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Events.cs
  index-editor-app/index-editor-app-engine/JsonClasses/MembersPage.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Specialties.cs
  index-editor-app/index-editor-app-engine/MembersHandler.cs
  index-editor-app/index-editor-app-engine/SpecialtyHandler.cs
  index-editor-app/index-editor-app/CreateSpecialtyForm.Designer.cs
  index-editor-app/index-editor-app/CreateSpecialtyForm.cs
  index-editor-app/index-editor-app/CreateSpecialtyForm.resx
  index-editor-app/index-editor-app/Form1.Designer.cs
  index-editor-app/index-editor-app/Form1.cs
  index-editor-app/index-editor-app/Members.cs
  index-editor-app/index-editor-app/index-editor-app.csproj.user
Labels: enhancement

#49 Sprint4 report
  Sprint Report/Sprint4-Report.md
Labels: sprint, high

#52 Added News Page
  front-end/index-vue/public/new.json
  front-end/index-vue/src/App.vue
  front-end/index-vue/src/components/NewsPage.vue
  front-end/index-vue/src/router/index.js
Labels: high

#54 Added Staff page
  front-end/index-vue/package.json
  front-end/index-vue/public/members.json
  front-end/index-vue/src/components/AboutUs.vue
  front-end/index-vue/src/components/Event.vue
  front-end/index-vue/src/components/Staff.vue
  front-end/index-vue/src/router/index.js
Labels: sprint, high

#58 Sprint5/editor app specialties
  index-editor-app/index-editor-app-engine/EventPage.cs
  index-editor-app/index-editor-app-engine/EventsData.json
  index-editor-app/index-editor-app-engine/EventsHandler.cs
  index-editor-app/index-editor-app-engine/IndexAPIClient.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Events.cs
  index-editor-app/index-editor-app-engine/JsonClasses/MembersPage.cs
  index-editor-app/index-editor-app-engine/JsonClasses/Specialties.cs
  index-editor-app/index-editor-app-engine/MembersHandler.cs
  index-editor-app/index-editor-app-engine/SpecialtyHandler.cs
  index-editor-app/index-editor-app/EventsForm.cs
  index-editor-app/index-editor-app/Form1.Designer.cs
  index-editor-app/index-editor-app/Form1.cs
  index-editor-app/index-editor-app/Members.cs
  index-editor-app/index-editor-app/Specialties.cs
  index-editor-app/index-editor-app/index-editor-app.csproj.user
Labels: enhancement
